site_name: OpenGarage Documentation
site_url: https://OpenGarage.github.io/OpenGarage-Firmware/
repo_url: https://github.com/OpenGarage/OpenGarage-Firmware

theme: readthedocs

nav:
  - 'Home': 'index.md'
  - 'Firmware v1.2.4':
    - 'User Manual': '1.2.4/manual.md'
    - 'API Reference': '1.2.4/api.md'
  - 'Archived':
    - 'Previous Manuals and API docs': 'archive.md'
extra_css:
  - custom.css
markdown_extensions:
  - attr_list
  - admonition
